[package]
name = "groupchat"
version = "0.1.0"
authors = ["Student <student@informatik.hu-berlin.de>"]
edition = "2021"

[lib]
name = "chatlib"

[dependencies]
mio = { version = "0.8", features = ["net", "os-poll"] }
async-std = "1.12"
futures = "0.3"
