[package]
name = "echo_server"
version = "0.1.0"
authors = ["Dorian Weber <weber@informatik.hu-berlin.de>"]
edition = "2021"

[dependencies]
mio = { version = "0.8", features = ["net", "os-poll"] }
async-std = "1.12"
futures = "0.3"
lazy_static = "1.4"
